name: go-check
on: push
jobs:
  style-check:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Format
          uses: Jerome1337/gofmt-action@v1.0.4
          with:
            gofmt-path: './cmd'
            gofmt-flags: '-l -d'
